export const toDoListConstants = {
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    GET_ALL_TODOS: 'GET_ALL_TODOS',
    GET_ALL_TODOS_FAILURE: 'GET_ALL_TODOS_FAILURE',
    CREATE_NEW_TODO_FAILURE: 'CREATE_NEW_TODO_FAILURE',
     
};

